name: Deploy static content to Pages

on:
  push:
    branches: ["main"]  # Garante que o workflow execute quando houver push na branch 'main'
  workflow_dispatch:  # Permite disparar o workflow manualmente da aba "Actions" no GitHub

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Baixa o código do repositório
        
      - name: Setup Pages
        uses: actions/configure-pages@v5  # Configura o ambiente do GitHub Pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Faz o upload de todos os arquivos do repositório

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Realiza o deploy para o GitHub Pages
